title: ThomasR.me
description: "âœŒğŸ» Personal website of Thomas 'Tom' Robinson"
image: /static/img/blondtommodrawing-500.jpg

baseurl: "" # no leading slash
url: https://thomasr.me
locale: en_GB

permalink: /:title/

sass:
  style: expanded
  load_paths:
    - static/css

compress_html:
  blanklines: true
  # ignore:
  #   envs: ["development"]

plugins:
  - jekyll-sitemap

exclude:
  - README.md
