title: ThomasR.me
description: "âœŒğŸ» Personal website of Thomas 'Tom' Robinson"
image: /static/img/blondtommodrawing-500.jpg

baseurl: "" # no trailing slash
url: https://thomasr.me
locale: en_GB

permalink: /:title/

sass:
  sass_dir: static/css
  style: compressed

highlighter: rouge

compress_html:
  blanklines: true
  comments: "all"
  ignore:
    envs: ["development"]

plugins:
  - jekyll-sitemap